# Netlify Configuration for Tr3ble Portfolio
# Optimized for SEO and Performance

[build]
  command = "bun run build"
  publish = "out"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/dev/null"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Build Plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = ["node_modules", ".next/cache"]

# Redirects for SPA routing and SEO
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["US"]}

# Force HTTPS redirect
[[redirects]]
  from = "http://tr3ble.dev/*"
  to = "https://tr3ble.dev/:splat"
  status = 301
  force = true

# Redirect www to non-www
[[redirects]]
  from = "https://www.tr3ble.dev/*"
  to = "https://tr3ble.dev/:splat"
  status = 301
  force = true

# Image optimization
[images]
  remote_images = [
    "https://source.unsplash.com/.*",
    "https://images.unsplash.com/.*",
    "https://ext.same-assets.com/.*",
    "https://ugc.same-assets.com/.*"
  ]

# Headers for static files (additional to _headers file)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions configuration (if needed in future)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Edge functions (if needed)
[edge_functions]
  directory = "netlify/edge-functions"

# Environment variables
[context.production.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"

# Form handling (if contact forms are added)
[forms]
  settings = true